name: WorkFlow para IC - DevSecOps

on:
  push:
    branches:
      - feat-devsecops

jobs:
  JTRPipeline:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        #- name: Imprimir Hola Mundo
          #run: echo "Hola Mundo desde GitHub Actions (Mi primer Job)"

        #Analisis SAST
        - name: Validando existencia de Proyecto en Sonarcloud
          id: validateProjectSonar
          run: |
            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{github.event.repository.name}}' -d 'organization=juliotabilo' -d 'project=${{github.event.repository.name}}' -d 'visibility=public'
            if [ $? -eq 0 ]; then
              echo "Proyecto creado o ya existe en SonarCloud"
              curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{github.event.repository.name}}'

            else
              echo "Error al crear el proyecto en SonarCloud"
              exit 1
            fi

        - name: Analisis SonarCloud
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          continue-on-error: true  # Esta línea hace que no haya quiebre en el Pipeline (A pesar que haya error sigue)

          # Analisis SCA
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'
        - name: Install dependencies
          run: npm install
          continue-on-error: true
        - name: Generar reporte HTML SCA
          run: |
            npm audit --json > audit.json
            npx npm-audit-html -i audit.json -o audit-report.html
        - name: Publicar reporte SCA como artefacto
          uses: actions/upload-artifact@v4
          with:
            name: sca-audit-report
            path: audit-report.html
        - name: SCA - npm audit (falla con vulnerabilidades)
          run: npm audit --audit-level=moderate


           
